/*
 * Copyright (C) 2014-2016 SonarSource SA
 * All rights reserved
 * mailto:contact AT sonarsource DOT com
 */
package com.sonarsource.ruleapi.externalspecifications.tools;

import com.sonarsource.ruleapi.domain.Rule;
import com.sonarsource.ruleapi.externalspecifications.AbstractReportableExternalTool;
import com.sonarsource.ruleapi.externalspecifications.CodingStandardRule;
import com.sonarsource.ruleapi.externalspecifications.HasLevel;
import com.sonarsource.ruleapi.externalspecifications.Implementability;
import com.sonarsource.ruleapi.utilities.Language;

import java.util.List;


public class ReSharper extends AbstractReportableExternalTool {

  private String toolName = "ReSharper";
  private Language language = Language.CSH;

  private String reportName = toolName + " " + language.getRspec();

  @Override
  public Language getLanguage() {

    return language;
  }

  @Override
  public CodingStandardRule[] getCodingStandardRules() {

    return ReSharperRule.values();
  }

  @Override
  public String getStandardName() {

    return reportName;
  }

  @Override
  public String getRSpecReferenceFieldName() {

    return toolName;
  }

  @Override
  public List<String> getRspecReferenceFieldValues(Rule rule) {

    return rule.getResharper();
  }

  @Override
  public void setRspecReferenceFieldValues(Rule rule, List<String> ids) {
    rule.setResharper(ids);
  }

  public enum Activation {
    UNKNOWN, DO_NOT_SHOW, SUGGESTION, HINT, WARNING, ERROR;
  }

  public enum ReSharperRule implements CodingStandardRule, HasLevel {
    ACCESSTODISPOSEDCLOSURE("AccessToDisposedClosure", Implementability.IMPLEMENTABLE, Activation.WARNING),
    ACCESSTOFOREACHVARIABLEINCLOSURE("AccessToForEachVariableInClosure", Implementability.IMPLEMENTABLE, Activation.WARNING),
    ACCESSTOMODIFIEDCLOSURE("AccessToModifiedClosure", Implementability.IMPLEMENTABLE, Activation.WARNING),
    ACCESSTOSTATICMEMBERVIADERIVEDTYPE("AccessToStaticMemberViaDerivedType", Implementability.REJECTED, Activation.WARNING),
    AMDDEPENDENCYPATHPROBLEM("AmdDependencyPathProblem", Implementability.IMPLEMENTABLE, Activation.DO_NOT_SHOW),
    AMDEXTERNALMODULE("AmdExternalModule", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    ANNOTATIONCONFLICTINHIERARCHY("AnnotationConflictInHierarchy", Implementability.REJECTED, Activation.WARNING),
    ANNOTATIONREDUNDANCYATVALUETYPE("AnnotationRedundancyAtValueType", Implementability.REJECTED, Activation.WARNING),
    ANNOTATIONREDUNDANCYINHIERARCHY("AnnotationRedundancyInHierarchy", Implementability.REJECTED, Activation.WARNING),
    ARRANGEATTRIBUTES("ArrangeAttributes", Implementability.IMPLEMENTABLE, Activation.DO_NOT_SHOW),
    ARRANGEMISSINGPARENTHESES("ArrangeMissingParentheses", Implementability.IMPLEMENTABLE, Activation.DO_NOT_SHOW),
    ARRANGEMODIFIERSORDER("ArrangeModifiersOrder", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    ARRANGEREDUNDANTPARENTHESES("ArrangeRedundantParentheses", Implementability.IMPLEMENTABLE, Activation.HINT),
    ARRANGESTATICMEMBERQUALIFIER("ArrangeStaticMemberQualifier", Implementability.IMPLEMENTABLE, Activation.WARNING),
    ARRANGETHISQUALIFIER("ArrangeThisQualifier", Implementability.IMPLEMENTABLE, Activation.WARNING),
    ARRANGETYPEMEMBERMODIFIERS("ArrangeTypeMemberModifiers", Implementability.IMPLEMENTABLE, Activation.HINT),
    ARRANGETYPEMODIFIERS("ArrangeTypeModifiers", Implementability.IMPLEMENTABLE, Activation.HINT),
    ASSIGNNULLTONOTNULLATTRIBUTE("AssignNullToNotNullAttribute", Implementability.REJECTED, Activation.WARNING),
    ASSIGNTOCONSTANT("AssignToConstant", Implementability.IMPLEMENTABLE, Activation.ERROR),
    ASSIGNEDVALUEWONTBEASSIGNEDTOCORRESPONDINGFIELD("AssignedValueWontBeAssignedToCorrespondingField", Implementability.IMPLEMENTABLE, Activation.WARNING),
    ASSIGNMENTINCONDITIONEXPRESSION("AssignmentInConditionExpression", Implementability.IMPLEMENTABLE, Activation.WARNING),
    ASSIGNMENTINCONDITIONALEXPRESSION("AssignmentInConditionalExpression", Implementability.IMPLEMENTABLE, Activation.WARNING),
    ASXX_PATHERROR("Asxx.PathError", Implementability.IMPLEMENTABLE, Activation.WARNING),
    ASXXERRORS("AsxxErrors", Implementability.IMPLEMENTABLE, Activation.ERROR),
    AUTOPROPERTYCANBEMADEGETONLY_GLOBAL("AutoPropertyCanBeMadeGetOnly.Global", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    AUTOPROPERTYCANBEMADEGETONLY_LOCAL("AutoPropertyCanBeMadeGetOnly.Local", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    BASEMEMBERHASPARAMS("BaseMemberHasParams", Implementability.IMPLEMENTABLE, Activation.WARNING),
    BASEMETHODCALLWITHDEFAULTPARAMETER("BaseMethodCallWithDefaultParameter", Implementability.IMPLEMENTABLE, Activation.WARNING),
    BASEOBJECTEQUALSISOBJECTEQUALS("BaseObjectEqualsIsObjectEquals", Implementability.IMPLEMENTABLE, Activation.WARNING),
    BASEOBJECTGETHASHCODECALLINGETHASHCODE("BaseObjectGetHashCodeCallInGetHashCode", Implementability.IMPLEMENTABLE, Activation.WARNING),
    BITWISEOPERATORONENUMWITHOUTFLAGS("BitwiseOperatorOnEnumWithoutFlags", Implementability.IMPLEMENTABLE, Activation.WARNING),
    BLOCKSCOPEREDECLARATION("BlockScopeRedeclaration", Implementability.IMPLEMENTABLE, Activation.ERROR),
    BUILDSCRIPTERRORS("BuildScriptErrors", Implementability.IMPLEMENTABLE, Activation.ERROR),
    BUILTINTYPEREFERENCESTYLE("BuiltInTypeReferenceStyle", Implementability.IMPLEMENTABLE, Activation.HINT),
    CSHARPERRORS("CSharpErrors", Implementability.IMPLEMENTABLE, Activation.ERROR),
    CSHARPWARNINGS_CS0108("CSharpWarnings::CS0108", Implementability.REJECTED, Activation.WARNING),
    CSHARPWARNINGS_CS0109("CSharpWarnings::CS0109", Implementability.REJECTED, Activation.WARNING),
    CSHARPWARNINGS_CS0162("CSharpWarnings::CS0162", Implementability.REJECTED, Activation.WARNING),
    CSHARPWARNINGS_CS0183("CSharpWarnings::CS0183", Implementability.REJECTED, Activation.WARNING),
    CSHARPWARNINGS_CS0184("CSharpWarnings::CS0184", Implementability.REJECTED, Activation.WARNING),
    CSHARPWARNINGS_CS0197("CSharpWarnings::CS0197", Implementability.REJECTED, Activation.WARNING),
    CSHARPWARNINGS_CS0252("CSharpWarnings::CS0252", Implementability.REJECTED, Activation.WARNING),
    CSHARPWARNINGS_CS0420("CSharpWarnings::CS0420", Implementability.REJECTED, Activation.WARNING),
    CSHARPWARNINGS_CS0465("CSharpWarnings::CS0465", Implementability.REJECTED, Activation.WARNING),
    CSHARPWARNINGS_CS0469("CSharpWarnings::CS0469", Implementability.REJECTED, Activation.WARNING),
    CSHARPWARNINGS_CS0612("CSharpWarnings::CS0612", Implementability.REJECTED, Activation.WARNING),
    CSHARPWARNINGS_CS0618("CSharpWarnings::CS0618", Implementability.REJECTED, Activation.WARNING),
    CSHARPWARNINGS_CS0628("CSharpWarnings::CS0628", Implementability.REJECTED, Activation.WARNING),
    CSHARPWARNINGS_CS0642("CSharpWarnings::CS0642", Implementability.REJECTED, Activation.WARNING),
    CSHARPWARNINGS_CS0657("CSharpWarnings::CS0657", Implementability.REJECTED, Activation.WARNING),
    CSHARPWARNINGS_CS0658("CSharpWarnings::CS0658", Implementability.REJECTED, Activation.WARNING),
    CSHARPWARNINGS_CS0659("CSharpWarnings::CS0659", Implementability.REJECTED, Activation.WARNING),
    CSHARPWARNINGS_CS0660("CSharpWarnings::CS0660", Implementability.REJECTED, Activation.WARNING),
    CSHARPWARNINGS_CS0665("CSharpWarnings::CS0665", Implementability.REJECTED, Activation.WARNING),
    CSHARPWARNINGS_CS0672("CSharpWarnings::CS0672", Implementability.REJECTED, Activation.WARNING),
    CSHARPWARNINGS_CS0693("CSharpWarnings::CS0693", Implementability.REJECTED, Activation.WARNING),
    CSHARPWARNINGS_CS1030("CSharpWarnings::CS1030", Implementability.REJECTED, Activation.WARNING),
    CSHARPWARNINGS_CS1058("CSharpWarnings::CS1058", Implementability.REJECTED, Activation.WARNING),
    CSHARPWARNINGS_CS1066("CSharpWarnings::CS1066", Implementability.REJECTED, Activation.WARNING),
    CSHARPWARNINGS_CS1522("CSharpWarnings::CS1522", Implementability.REJECTED, Activation.WARNING),
    CSHARPWARNINGS_CS1570("CSharpWarnings::CS1570", Implementability.REJECTED, Activation.WARNING),
    CSHARPWARNINGS_CS1571("CSharpWarnings::CS1571", Implementability.REJECTED, Activation.WARNING),
    CSHARPWARNINGS_CS1573("CSharpWarnings::CS1573", Implementability.REJECTED, Activation.WARNING),
    CSHARPWARNINGS_CS1574("CSharpWarnings::CS1574", Implementability.REJECTED, Activation.WARNING),
    CSHARPWARNINGS_CS1580("CSharpWarnings::CS1580", Implementability.REJECTED, Activation.WARNING),
    CSHARPWARNINGS_CS1584("CSharpWarnings::CS1584", Implementability.REJECTED, Activation.WARNING),
    CSHARPWARNINGS_CS1587("CSharpWarnings::CS1587", Implementability.REJECTED, Activation.WARNING),
    CSHARPWARNINGS_CS1589("CSharpWarnings::CS1589", Implementability.REJECTED, Activation.WARNING),
    CSHARPWARNINGS_CS1590("CSharpWarnings::CS1590", Implementability.REJECTED, Activation.WARNING),
    CSHARPWARNINGS_CS1591("CSharpWarnings::CS1591", Implementability.REJECTED, Activation.WARNING),
    CSHARPWARNINGS_CS1592("CSharpWarnings::CS1592", Implementability.REJECTED, Activation.WARNING),
    CSHARPWARNINGS_CS1710("CSharpWarnings::CS1710", Implementability.REJECTED, Activation.WARNING),
    CSHARPWARNINGS_CS1712("CSharpWarnings::CS1712", Implementability.REJECTED, Activation.WARNING),
    CSHARPWARNINGS_CS1717("CSharpWarnings::CS1717", Implementability.REJECTED, Activation.WARNING),
    CSHARPWARNINGS_CS1723("CSharpWarnings::CS1723", Implementability.REJECTED, Activation.WARNING),
    CSHARPWARNINGS_CS1911("CSharpWarnings::CS1911", Implementability.REJECTED, Activation.WARNING),
    CSHARPWARNINGS_CS1957("CSharpWarnings::CS1957", Implementability.REJECTED, Activation.WARNING),
    CSHARPWARNINGS_CS1998("CSharpWarnings::CS1998", Implementability.REJECTED, Activation.WARNING),
    CSHARPWARNINGS_CS4014("CSharpWarnings::CS4014", Implementability.REJECTED, Activation.WARNING),
    CSHARPWARNINGS_CS7095("CSharpWarnings::CS7095", Implementability.REJECTED, Activation.WARNING),
    CSHARPWARNINGS_CS8094("CSharpWarnings::CS8094", Implementability.REJECTED, Activation.WARNING),
    CSHARPWARNINGS_WME006("CSharpWarnings::WME006", Implementability.REJECTED, Activation.WARNING),
    CALLERCALLEEUSING("CallerCalleeUsing", Implementability.IMPLEMENTABLE, Activation.WARNING),
    CALLERCALLEEUSINGERROR("CallerCalleeUsingError", Implementability.IMPLEMENTABLE, Activation.ERROR),
    CANBEREPLACEDWITHTRYCASTANDCHECKFORNULL("CanBeReplacedWithTryCastAndCheckForNull", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    CANNOTAPPLYEQUALITYOPERATORTOTYPE("CannotApplyEqualityOperatorToType", Implementability.REJECTED, Activation.WARNING),
    CHECKFORREFERENCEEQUALITYINSTEAD_1("CheckForReferenceEqualityInstead.1", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    CHECKFORREFERENCEEQUALITYINSTEAD_2("CheckForReferenceEqualityInstead.2", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    CHECKNAMESPACE("CheckNamespace", Implementability.IMPLEMENTABLE, Activation.WARNING),
    CLASS("Class", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    CLASSCANBESEALED_GLOBAL("ClassCanBeSealed.Global", Implementability.IMPLEMENTABLE, Activation.DO_NOT_SHOW),
    CLASSCANBESEALED_LOCAL("ClassCanBeSealed.Local", Implementability.IMPLEMENTABLE, Activation.DO_NOT_SHOW),
    CLASSCANNOTBEINSTANTIATED("ClassCannotBeInstantiated", Implementability.IMPLEMENTABLE, Activation.WARNING),
    CLASSNEVERINSTANTIATED_GLOBAL("ClassNeverInstantiated.Global", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    CLASSNEVERINSTANTIATED_LOCAL("ClassNeverInstantiated.Local", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    CLASSWITHVIRTUALMEMBERSNEVERINHERITED_GLOBAL("ClassWithVirtualMembersNeverInherited.Global", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    CLASSWITHVIRTUALMEMBERSNEVERINHERITED_LOCAL("ClassWithVirtualMembersNeverInherited.Local", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    CLOSUREONMODIFIEDVARIABLE("ClosureOnModifiedVariable", Implementability.IMPLEMENTABLE, Activation.WARNING),
    COVARIANTARRAYCONVERSION("CoVariantArrayConversion", Implementability.IMPLEMENTABLE, Activation.WARNING),
    CODESMELL("CodeSmell", Implementability.IMPLEMENTABLE, Activation.ERROR),
    COERCEDEQUALSUSING("CoercedEqualsUsing", Implementability.IMPLEMENTABLE, Activation.WARNING),
    COERCEDEQUALSUSINGWITHNULLUNDEFINED("CoercedEqualsUsingWithNullUndefined", Implementability.IMPLEMENTABLE, Activation.DO_NOT_SHOW),
    COLLECTIONNEVERQUERIED_GLOBAL("CollectionNeverQueried.Global", Implementability.IMPLEMENTABLE, Activation.WARNING),
    COLLECTIONNEVERQUERIED_LOCAL("CollectionNeverQueried.Local", Implementability.IMPLEMENTABLE, Activation.WARNING),
    COLLECTIONNEVERUPDATED_GLOBAL("CollectionNeverUpdated.Global", Implementability.IMPLEMENTABLE, Activation.WARNING),
    COLLECTIONNEVERUPDATED_LOCAL("CollectionNeverUpdated.Local", Implementability.IMPLEMENTABLE, Activation.WARNING),
    COMMONJSEXTERNALMODULE("CommonJsExternalModule", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    COMPARENONCONSTRAINEDGENERICWITHNULL("CompareNonConstrainedGenericWithNull", Implementability.IMPLEMENTABLE, Activation.DO_NOT_SHOW),
    COMPAREOFFLOATSBYEQUALITYOPERATOR("CompareOfFloatsByEqualityOperator", Implementability.IMPLEMENTABLE, Activation.WARNING),
    CONDITIONISALWAYSTRUEORFALSE("ConditionIsAlwaysTrueOrFalse", Implementability.IMPLEMENTABLE, Activation.WARNING),
    CONDITIONALTERNARYEQUALBRANCH("ConditionalTernaryEqualBranch", Implementability.IMPLEMENTABLE, Activation.WARNING),
    CONSTANTCONDITIONALACCESSQUALIFIER("ConstantConditionalAccessQualifier", Implementability.IMPLEMENTABLE, Activation.WARNING),
    CONSTANTNULLCOALESCINGCONDITION("ConstantNullCoalescingCondition", Implementability.IMPLEMENTABLE, Activation.WARNING),
    CONSTRUCTORCALLNOTUSED("ConstructorCallNotUsed", Implementability.IMPLEMENTABLE, Activation.WARNING),
    CONSTRUCTORINITIALIZERLOOP("ConstructorInitializerLoop", Implementability.REJECTED, Activation.WARNING),
    CONTEXTVALUEISPROVIDED("ContextValueIsProvided", Implementability.IMPLEMENTABLE, Activation.DO_NOT_SHOW),
    CONTRACTANNOTATIONNOTPARSED("ContractAnnotationNotParsed", Implementability.REJECTED, Activation.WARNING),
    CONVERTCLOSURETOMETHODGROUP("ConvertClosureToMethodGroup", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    CONVERTCONDITIONALTERNARYTONULLCOALESCING("ConvertConditionalTernaryToNullCoalescing", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    CONVERTIFDOTOWHILE("ConvertIfDoToWhile", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    CONVERTIFSTATEMENTTOCONDITIONALTERNARYEXPRESSION("ConvertIfStatementToConditionalTernaryExpression", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    CONVERTIFSTATEMENTTONULLCOALESCINGEXPRESSION("ConvertIfStatementToNullCoalescingExpression", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    CONVERTIFSTATEMENTTORETURNSTATEMENT("ConvertIfStatementToReturnStatement", Implementability.IMPLEMENTABLE, Activation.HINT),
    CONVERTIFSTATEMENTTOSWITCHSTATEMENT("ConvertIfStatementToSwitchStatement", Implementability.IMPLEMENTABLE, Activation.HINT),
    CONVERTIFTOOREXPRESSION("ConvertIfToOrExpression", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    CONVERTMETHODTOEXPRESSIONBODY("ConvertMethodToExpressionBody", Implementability.IMPLEMENTABLE, Activation.DO_NOT_SHOW),
    CONVERTNULLABLETOSHORTFORM("ConvertNullableToShortForm", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    CONVERTPROPERTYTOEXPRESSIONBODY("ConvertPropertyToExpressionBody", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    CONVERTTOAUTOPROPERTY("ConvertToAutoProperty", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    CONVERTTOAUTOPROPERTYWHENPOSSIBLE("ConvertToAutoPropertyWhenPossible", Implementability.IMPLEMENTABLE, Activation.HINT),
    CONVERTTOAUTOPROPERTYWITHPRIVATESETTER("ConvertToAutoPropertyWithPrivateSetter", Implementability.IMPLEMENTABLE, Activation.HINT),
    CONVERTTOCONSTANT_GLOBAL("ConvertToConstant.Global", Implementability.IMPLEMENTABLE, Activation.HINT),
    CONVERTTOCONSTANT_LOCAL("ConvertToConstant.Local", Implementability.IMPLEMENTABLE, Activation.HINT),
    CONVERTTOEXPRESSIONBODYWHENPOSSIBLE("ConvertToExpressionBodyWhenPossible", Implementability.IMPLEMENTABLE, Activation.DO_NOT_SHOW),
    CONVERTTOLAMBDAEXPRESSION("ConvertToLambdaExpression", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    CONVERTTOLAMBDAEXPRESSIONWHENPOSSIBLE("ConvertToLambdaExpressionWhenPossible", Implementability.IMPLEMENTABLE, Activation.DO_NOT_SHOW),
    CONVERTTOSTATICCLASS("ConvertToStaticClass", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    CONVERTTOVBAUTOPROPERTY("ConvertToVbAutoProperty", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    CONVERTTOVBAUTOPROPERTYWHENPOSSIBLE("ConvertToVbAutoPropertyWhenPossible", Implementability.IMPLEMENTABLE, Activation.HINT),
    CONVERTTOVBAUTOPROPERTYWITHPRIVATESETTER("ConvertToVbAutoPropertyWithPrivateSetter", Implementability.IMPLEMENTABLE, Activation.HINT),
    CREATESPECIALIZEDOVERLOAD("CreateSpecializedOverload", Implementability.IMPLEMENTABLE, Activation.HINT),
    CYCLICREFERENCECOMMENT("CyclicReferenceComment", Implementability.IMPLEMENTABLE, Activation.DO_NOT_SHOW),
    DECLARATIONHIDES("DeclarationHides", Implementability.IMPLEMENTABLE, Activation.HINT),
    DEFAULTVALUEATTRIBUTEFOROPTIONALPARAMETER("DefaultValueAttributeForOptionalParameter", Implementability.IMPLEMENTABLE, Activation.WARNING),
    DELEGATESUBTRACTION("DelegateSubtraction", Implementability.IMPLEMENTABLE, Activation.WARNING),
    DELETINGNONQUALIFIEDREFERENCE("DeletingNonQualifiedReference", Implementability.IMPLEMENTABLE, Activation.ERROR),
    DOUBLENEGATIONOFBOOLEAN("DoubleNegationOfBoolean", Implementability.IMPLEMENTABLE, Activation.WARNING),
    DOUBLENEGATIONOPERATOR("DoubleNegationOperator", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    DUPLICATEREFERENCECOMMENT("DuplicateReferenceComment", Implementability.IMPLEMENTABLE, Activation.WARNING),
    DUPLICATERESOURCE("DuplicateResource", Implementability.REJECTED, Activation.WARNING),
    DUPLICATINGPARAMETERDECLARATIONERROR("DuplicatingParameterDeclarationError", Implementability.IMPLEMENTABLE, Activation.ERROR),
    DUPLICATINGPROPERTYDECLARATIONERROR("DuplicatingPropertyDeclarationError", Implementability.IMPLEMENTABLE, Activation.ERROR),
    DYNAMICSHIFTRIGHTOPISNOTINT("DynamicShiftRightOpIsNotInt", Implementability.IMPLEMENTABLE, Activation.WARNING),
    EMPTYCONSTRUCTOR("EmptyConstructor", Implementability.IMPLEMENTABLE, Activation.WARNING),
    EMPTYDESTRUCTOR("EmptyDestructor", Implementability.IMPLEMENTABLE, Activation.WARNING),
    EMPTYEMBEDDEDSTATEMENT("EmptyEmbeddedStatement", Implementability.IMPLEMENTABLE, Activation.WARNING),
    EMPTYFORSTATEMENT("EmptyForStatement", Implementability.IMPLEMENTABLE, Activation.WARNING),
    EMPTYGENERALCATCHCLAUSE("EmptyGeneralCatchClause", Implementability.IMPLEMENTABLE, Activation.WARNING),
    EMPTYNAMESPACE("EmptyNamespace", Implementability.IMPLEMENTABLE, Activation.WARNING),
    EMPTYRETURNVALUEFORTYPEANNOTATEDFUNCTION("EmptyReturnValueForTypeAnnotatedFunction", Implementability.IMPLEMENTABLE, Activation.WARNING),
    EMPTYSTATEMENT("EmptyStatement", Implementability.IMPLEMENTABLE, Activation.WARNING),
    ENUMUNDERLYINGTYPEISINT("EnumUnderlyingTypeIsInt", Implementability.IMPLEMENTABLE, Activation.WARNING),
    ENUMERABLESUMINEXPLICITUNCHECKEDCONTEXT("EnumerableSumInExplicitUncheckedContext", Implementability.IMPLEMENTABLE, Activation.WARNING),
    EQUALEXPRESSIONCOMPARISON("EqualExpressionComparison", Implementability.IMPLEMENTABLE, Activation.WARNING),
    ES6FEATURE("Es6Feature", Implementability.IMPLEMENTABLE, Activation.ERROR),
    EVALARGUMENTSNAMEERROR("EvalArgumentsNameError", Implementability.IMPLEMENTABLE, Activation.ERROR),
    EVENTNEVERINVOKED("EventNeverInvoked", Implementability.IMPLEMENTABLE, Activation.WARNING),
    EVENTNEVERINVOKED_GLOBAL("EventNeverInvoked.Global", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    EVENTNEVERSUBSCRIBEDTO_GLOBAL("EventNeverSubscribedTo.Global", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    EVENTNEVERSUBSCRIBEDTO_LOCAL("EventNeverSubscribedTo.Local", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    EVENTUNSUBSCRIPTIONVIAANONYMOUSDELEGATE("EventUnsubscriptionViaAnonymousDelegate", Implementability.IMPLEMENTABLE, Activation.WARNING),
    EXPERIMENTALFEATURE("ExperimentalFeature", Implementability.IMPLEMENTABLE, Activation.ERROR),
    EXPLICITCALLERINFOARGUMENT("ExplicitCallerInfoArgument", Implementability.IMPLEMENTABLE, Activation.WARNING),
    EXPRESSIONISALWAYSNULL("ExpressionIsAlwaysNull", Implementability.IMPLEMENTABLE, Activation.WARNING),
    FIELDCANBEMADEREADONLY_GLOBAL("FieldCanBeMadeReadOnly.Global", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    FIELDCANBEMADEREADONLY_LOCAL("FieldCanBeMadeReadOnly.Local", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    FORCANBECONVERTEDTOFOREACH("ForCanBeConvertedToForeach", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    FORSTATEMENTCONDITIONISTRUE("ForStatementConditionIsTrue", Implementability.IMPLEMENTABLE, Activation.WARNING),
    FORMATSTRINGPLACEHOLDERSMISMATCH("FormatStringPlaceholdersMismatch", Implementability.IMPLEMENTABLE, Activation.WARNING),
    FORMATSTRINGPROBLEM("FormatStringProblem", Implementability.IMPLEMENTABLE, Activation.WARNING),
    FUNCTIONCOMPLEXITYOVERFLOW("FunctionComplexityOverflow", Implementability.IMPLEMENTABLE, Activation.DO_NOT_SHOW),
    FUNCTIONNEVERRETURNS("FunctionNeverReturns", Implementability.REJECTED, Activation.WARNING),
    FUNCTIONPARAMETERNAMEDARGUMENTS("FunctionParameterNamedArguments", Implementability.IMPLEMENTABLE, Activation.WARNING),
    FUNCTIONRECURSIVEONALLPATHS("FunctionRecursiveOnAllPaths", Implementability.IMPLEMENTABLE, Activation.WARNING),
    FUNCTIONUSEDOUTOFSCOPE("FunctionUsedOutOfScope", Implementability.IMPLEMENTABLE, Activation.WARNING),
    FUNCTIONSUSEDBEFOREDECLARED("FunctionsUsedBeforeDeclared", Implementability.IMPLEMENTABLE, Activation.DO_NOT_SHOW),
    GCSUPPRESSFINALIZEFORTYPEWITHOUTDESTRUCTOR("GCSuppressFinalizeForTypeWithoutDestructor", Implementability.IMPLEMENTABLE, Activation.WARNING),
    HEURISTICUNREACHABLECODE("HeuristicUnreachableCode", Implementability.IMPLEMENTABLE, Activation.WARNING),
    HEURISTICALLYUNREACHABLECODE("HeuristicallyUnreachableCode", Implementability.IMPLEMENTABLE, Activation.WARNING),
    IDENTIFIERHIGHLIGHTINGS("IdentifierHighlightings", Implementability.IMPLEMENTABLE, Activation.ERROR),
    IMPLICITANYERROR("ImplicitAnyError", Implementability.IMPLEMENTABLE, Activation.ERROR),
    IMPLICITANYTYPEWARNING("ImplicitAnyTypeWarning", Implementability.IMPLEMENTABLE, Activation.WARNING),
    IMPLICITLYCAPTUREDCLOSURE("ImplicitlyCapturedClosure", Implementability.IMPLEMENTABLE, Activation.HINT),
    IMPUREMETHODCALLONREADONLYVALUEFIELD("ImpureMethodCallOnReadonlyValueField", Implementability.IMPLEMENTABLE, Activation.WARNING),
    INCONSISTENTLYSYNCHRONIZEDFIELD("InconsistentlySynchronizedField", Implementability.IMPLEMENTABLE, Activation.WARNING),
    INCORRECTOPERANDINTYPEOFCOMPARISON("IncorrectOperandInTypeOfComparison", Implementability.IMPLEMENTABLE, Activation.WARNING),
    INTERNALMODULE("InternalModule", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    INTERPOLATEDSTRINGEXPRESSIONISNOTIFORMATTABLE("InterpolatedStringExpressionIsNotIFormattable", Implementability.IMPLEMENTABLE, Activation.WARNING),
    INTRODUCEOPTIONALPARAMETERS_GLOBAL("IntroduceOptionalParameters.Global", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    INTRODUCEOPTIONALPARAMETERS_LOCAL("IntroduceOptionalParameters.Local", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    INTRODUCEVARIABLETOAPPLYGUARD("IntroduceVariableToApplyGuard", Implementability.IMPLEMENTABLE, Activation.HINT),
    INVERTCONDITION_1("InvertCondition.1", Implementability.IMPLEMENTABLE, Activation.HINT),
    INVERTIF("InvertIf", Implementability.IMPLEMENTABLE, Activation.HINT),
    INVOCATIONISSKIPPED("InvocationIsSkipped", Implementability.IMPLEMENTABLE, Activation.HINT),
    INVOKEASEXTENSIONMETHOD("InvokeAsExtensionMethod", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    ISEXPRESSIONALWAYSFALSE("IsExpressionAlwaysFalse", Implementability.IMPLEMENTABLE, Activation.WARNING),
    ISEXPRESSIONALWAYSTRUE("IsExpressionAlwaysTrue", Implementability.IMPLEMENTABLE, Activation.WARNING),
    ITERATORMETHODRESULTISIGNORED("IteratorMethodResultIsIgnored", Implementability.IMPLEMENTABLE, Activation.WARNING),
    JOINDECLARATIONANDINITIALIZER("JoinDeclarationAndInitializer", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    JOINDECLARATIONANDINITIALIZERJS("JoinDeclarationAndInitializerJs", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    JSPATHNOTFOUND("JsPathNotFound", Implementability.IMPLEMENTABLE, Activation.ERROR),
    LAMBDA("Lambda", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    LESSSPECIFICOVERLOADTHANMAINSIGNATURE("LessSpecificOverloadThanMainSignature", Implementability.IMPLEMENTABLE, Activation.WARNING),
    LOCALFUNCTIONREDEFINEDLATER("LocalFunctionRedefinedLater", Implementability.IMPLEMENTABLE, Activation.WARNING),
    LOCALVARIABLEHIDESMEMBER("LocalVariableHidesMember", Implementability.IMPLEMENTABLE, Activation.WARNING),
    LOCALIZABLEELEMENT("LocalizableElement", Implementability.IMPLEMENTABLE, Activation.WARNING),
    LONGLITERALENDINGLOWERL("LongLiteralEndingLowerL", Implementability.IMPLEMENTABLE, Activation.WARNING),
    LOOPCANBECONVERTEDTOQUERY("LoopCanBeConvertedToQuery", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    LOOPCANBEPARTLYCONVERTEDTOQUERY("LoopCanBePartlyConvertedToQuery", Implementability.IMPLEMENTABLE, Activation.HINT),
    LOOPVARIABLEISNEVERCHANGEDINSIDELOOP("LoopVariableIsNeverChangedInsideLoop", Implementability.IMPLEMENTABLE, Activation.WARNING),
    MEANINGLESSDEFAULTPARAMETERVALUE("MeaninglessDefaultParameterValue", Implementability.IMPLEMENTABLE, Activation.WARNING),
    MEMBERCANBEINTERNAL("MemberCanBeInternal", Implementability.IMPLEMENTABLE, Activation.DO_NOT_SHOW),
    MEMBERCANBEMADESTATIC_GLOBAL("MemberCanBeMadeStatic.Global", Implementability.IMPLEMENTABLE, Activation.HINT),
    MEMBERCANBEMADESTATIC_LOCAL("MemberCanBeMadeStatic.Local", Implementability.REJECTED, Activation.HINT),
    MEMBERCANBEPRIVATE_GLOBAL("MemberCanBePrivate.Global", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    MEMBERCANBEPRIVATE_LOCAL("MemberCanBePrivate.Local", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    MEMBERCANBEPROTECTED_GLOBAL("MemberCanBeProtected.Global", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    MEMBERCANBEPROTECTED_LOCAL("MemberCanBeProtected.Local", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    MEMBERHIDESSTATICFROMOUTERCLASS("MemberHidesStaticFromOuterClass", Implementability.IMPLEMENTABLE, Activation.WARNING),
    MEMBERINITIALIZERVALUEIGNORED("MemberInitializerValueIgnored", Implementability.IMPLEMENTABLE, Activation.WARNING),
    MERGECONDITIONALEXPRESSION("MergeConditionalExpression", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    MERGESEQUENTIALCHECKS("MergeSequentialChecks", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    METHOD("Method", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    METHODOVERLOADWITHOPTIONALPARAMETER("MethodOverloadWithOptionalParameter", Implementability.IMPLEMENTABLE, Activation.WARNING),
    METHODSUPPORTSCANCELLATION("MethodSupportsCancellation", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    MISSINGATTRIBUTE("MissingAttribute", Implementability.IMPLEMENTABLE, Activation.WARNING),
    MISSINGHASOWNPROPERTYINFOREACH("MissingHasOwnPropertyInForeach", Implementability.IMPLEMENTABLE, Activation.WARNING),
    MORESPECIFICFOREACHVARIABLETYPEAVAILABLE("MoreSpecificForeachVariableTypeAvailable", Implementability.REJECTED, Activation.SUGGESTION),
    MORESPECIFICSIGNATUREAFTERLESSSPECIFIC("MoreSpecificSignatureAfterLessSpecific", Implementability.IMPLEMENTABLE, Activation.WARNING),
    MULTIPLENULLABLEATTRIBUTESUSAGE("MultipleNullableAttributesUsage", Implementability.REJECTED, Activation.WARNING),
    MULTIPLEORDERBY("MultipleOrderBy", Implementability.IMPLEMENTABLE, Activation.WARNING),
    MULTIPLEOUTPUTTAGS("MultipleOutputTags", Implementability.REJECTED, Activation.WARNING),
    MUSTUSERETURNVALUE("MustUseReturnValue", Implementability.IMPLEMENTABLE, Activation.WARNING),
    NATIVETYPEPROTOTYPEEXTENDING("NativeTypePrototypeExtending", Implementability.IMPLEMENTABLE, Activation.WARNING),
    NATIVETYPEPROTOTYPEOVERWRITING("NativeTypePrototypeOverwriting", Implementability.IMPLEMENTABLE, Activation.WARNING),
    NEGATIVEEQUALITYEXPRESSION("NegativeEqualityExpression", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    NONASSIGNEDCONSTANT("NonAssignedConstant", Implementability.IMPLEMENTABLE, Activation.ERROR),
    NONREADONLYMEMBERINGETHASHCODE("NonReadonlyMemberInGetHashCode", Implementability.IMPLEMENTABLE, Activation.WARNING),
    NONVOLATILEFIELDINDOUBLECHECKLOCKING("NonVolatileFieldInDoubleCheckLocking", Implementability.IMPLEMENTABLE, Activation.WARNING),
    NOTACCESSEDFIELD_COMPILER("NotAccessedField.Compiler", Implementability.REJECTED, Activation.WARNING),
    NOTACCESSEDFIELD_GLOBAL("NotAccessedField.Global", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    NOTACCESSEDFIELD_LOCAL("NotAccessedField.Local", Implementability.IMPLEMENTABLE, Activation.WARNING),
    NOTACCESSEDVARIABLE("NotAccessedVariable", Implementability.IMPLEMENTABLE, Activation.WARNING),
    NOTACCESSEDVARIABLE_COMPILER("NotAccessedVariable.Compiler", Implementability.REJECTED, Activation.WARNING),
    NOTDECLAREDINPARENTCULTURE("NotDeclaredInParentCulture", Implementability.REJECTED, Activation.WARNING),
    NOTNULLMEMBERISNOTINITIALIZED("NotNullMemberIsNotInitialized", Implementability.IMPLEMENTABLE, Activation.WARNING),
    NOTOVERRIDENINSPECIFICCULTURE("NotOverridenInSpecificCulture", Implementability.REJECTED, Activation.WARNING),
    NOTRESOLVEDINTEXT("NotResolvedInText", Implementability.IMPLEMENTABLE, Activation.WARNING),
    OBJECTCREATIONASSTATEMENT("ObjectCreationAsStatement", Implementability.IMPLEMENTABLE, Activation.WARNING),
    OBJECTDESTRUCTURINGWITHOUTPARENTHESES("ObjectDestructuringWithoutParentheses", Implementability.IMPLEMENTABLE, Activation.ERROR),
    OBSOLETEELEMENT("ObsoleteElement", Implementability.IMPLEMENTABLE, Activation.WARNING),
    OBSOLETEELEMENTERROR("ObsoleteElementError", Implementability.IMPLEMENTABLE, Activation.ERROR),
    OCTALLITERALSNOTALLOWEDERROR("OctalLiteralsNotAllowedError", Implementability.IMPLEMENTABLE, Activation.ERROR),
    ONEWAYOPERATIONCONTRACTWITHRETURNTYPE("OneWayOperationContractWithReturnType", Implementability.IMPLEMENTABLE, Activation.WARNING),
    OPERATIONCONTRACTWITHOUTSERVICECONTRACT("OperationContractWithoutServiceContract", Implementability.IMPLEMENTABLE, Activation.WARNING),
    OPERATORISCANBEUSED("OperatorIsCanBeUsed", Implementability.IMPLEMENTABLE, Activation.WARNING),
    OPTIONALPARAMETERHIERARCHYMISMATCH("OptionalParameterHierarchyMismatch", Implementability.IMPLEMENTABLE, Activation.WARNING),
    OPTIONALPARAMETERREFOUT("OptionalParameterRefOut", Implementability.IMPLEMENTABLE, Activation.WARNING),
    OUTPUTTAGREQUIRED("OutputTagRequired", Implementability.REJECTED, Activation.WARNING),
    OVERLOADSIGNATUREINFERRING("OverloadSignatureInferring", Implementability.IMPLEMENTABLE, Activation.HINT),
    OVERRIDENWITHEMPTYVALUE("OverridenWithEmptyValue", Implementability.REJECTED, Activation.WARNING),
    OVERRIDENWITHSAMEVALUE("OverridenWithSameValue", Implementability.REJECTED, Activation.SUGGESTION),
    PARAMETERDOESNTMAKEANYSENSE("ParameterDoesntMakeAnySense", Implementability.IMPLEMENTABLE, Activation.WARNING),
    PARAMETERHIDESMEMBER("ParameterHidesMember", Implementability.IMPLEMENTABLE, Activation.WARNING),
    PARAMETERTYPECANBEENUMERABLE_GLOBAL("ParameterTypeCanBeEnumerable.Global", Implementability.IMPLEMENTABLE, Activation.HINT),
    PARAMETERTYPECANBEENUMERABLE_LOCAL("ParameterTypeCanBeEnumerable.Local", Implementability.IMPLEMENTABLE, Activation.HINT),
    PARTIALMETHODPARAMETERNAMEMISMATCH("PartialMethodParameterNameMismatch", Implementability.IMPLEMENTABLE, Activation.WARNING),
    PARTIALMETHODWITHSINGLEPART("PartialMethodWithSinglePart", Implementability.IMPLEMENTABLE, Activation.WARNING),
    PARTIALTYPEWITHSINGLEPART("PartialTypeWithSinglePart", Implementability.IMPLEMENTABLE, Activation.WARNING),
    POLYMORPHICFIELDLIKEEVENTINVOCATION("PolymorphicFieldLikeEventInvocation", Implementability.IMPLEMENTABLE, Activation.WARNING),
    POSSIBLEASSIGNMENTTOREADONLYFIELD("PossibleAssignmentToReadonlyField", Implementability.IMPLEMENTABLE, Activation.WARNING),
    POSSIBLEINFINITEINHERITANCE("PossibleInfiniteInheritance", Implementability.IMPLEMENTABLE, Activation.WARNING),
    POSSIBLEINTENDEDRETHROW("PossibleIntendedRethrow", Implementability.IMPLEMENTABLE, Activation.WARNING),
    POSSIBLEINTERFACEMEMBERAMBIGUITY("PossibleInterfaceMemberAmbiguity", Implementability.IMPLEMENTABLE, Activation.WARNING),
    POSSIBLEINVALIDCASTEXCEPTION("PossibleInvalidCastException", Implementability.IMPLEMENTABLE, Activation.WARNING),
    POSSIBLEINVALIDCASTEXCEPTIONINFOREACHLOOP("PossibleInvalidCastExceptionInForeachLoop", Implementability.IMPLEMENTABLE, Activation.WARNING),
    POSSIBLEINVALIDOPERATIONEXCEPTION("PossibleInvalidOperationException", Implementability.IMPLEMENTABLE, Activation.WARNING),
    POSSIBLELOSSOFFRACTION("PossibleLossOfFraction", Implementability.IMPLEMENTABLE, Activation.WARNING),
    POSSIBLEMISTAKENARGUMENT("PossibleMistakenArgument", Implementability.IMPLEMENTABLE, Activation.WARNING),
    POSSIBLEMISTAKENCALLTOGETTYPE_1("PossibleMistakenCallToGetType.1", Implementability.IMPLEMENTABLE, Activation.WARNING),
    POSSIBLEMISTAKENCALLTOGETTYPE_2("PossibleMistakenCallToGetType.2", Implementability.IMPLEMENTABLE, Activation.WARNING),
    POSSIBLEMULTIPLEENUMERATION("PossibleMultipleEnumeration", Implementability.IMPLEMENTABLE, Activation.WARNING),
    POSSIBLEMULTIPLEWRITEACCESSINDOUBLECHECKLOCKING("PossibleMultipleWriteAccessInDoubleCheckLocking", Implementability.IMPLEMENTABLE, Activation.WARNING),
    POSSIBLENULLREFERENCEEXCEPTION("PossibleNullReferenceException", Implementability.IMPLEMENTABLE, Activation.WARNING),
    POSSIBLEUNINTENDEDREFERENCECOMPARISON("PossibleUnintendedReferenceComparison", Implementability.IMPLEMENTABLE, Activation.WARNING),
    POSSIBLYINCORRECTLYBROKENSTATEMENT("PossiblyIncorrectlyBrokenStatement", Implementability.IMPLEMENTABLE, Activation.WARNING),
    POSSIBLYMISTAKENUSEOFPARAMSMETHOD("PossiblyMistakenUseOfParamsMethod", Implementability.IMPLEMENTABLE, Activation.WARNING),
    PRIVATEFIELDCANBECONVERTEDTOLOCALVARIABLE("PrivateFieldCanBeConvertedToLocalVariable", Implementability.IMPLEMENTABLE, Activation.WARNING),
    PROPERTYNOTRESOLVED("PropertyNotResolved", Implementability.REJECTED, Activation.ERROR),
    PROTOBUFERRORS("ProtobufErrors", Implementability.IMPLEMENTABLE, Activation.ERROR),
    PUBLICCONSTRUCTORINABSTRACTCLASS("PublicConstructorInAbstractClass", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    PUREATTRIBUTEONVOIDMETHOD("PureAttributeOnVoidMethod", Implementability.IMPLEMENTABLE, Activation.WARNING),
    QUANTIFIERAFTERACHOR("QuantifierAfterAchor", Implementability.IMPLEMENTABLE, Activation.WARNING),
    READACCESSINDOUBLECHECKLOCKING("ReadAccessInDoubleCheckLocking", Implementability.IMPLEMENTABLE, Activation.WARNING),
    REDUNDANTANONYMOUSTYPEPROPERTYNAME("RedundantAnonymousTypePropertyName", Implementability.IMPLEMENTABLE, Activation.WARNING),
    REDUNDANTARGUMENTDEFAULTVALUE("RedundantArgumentDefaultValue", Implementability.IMPLEMENTABLE, Activation.WARNING),
    REDUNDANTARGUMENTNAME("RedundantArgumentName", Implementability.IMPLEMENTABLE, Activation.HINT),
    REDUNDANTARGUMENTNAMEFORLITERALEXPRESSION("RedundantArgumentNameForLiteralExpression", Implementability.IMPLEMENTABLE, Activation.HINT),
    REDUNDANTARRAYCREATIONEXPRESSION("RedundantArrayCreationExpression", Implementability.IMPLEMENTABLE, Activation.HINT),
    REDUNDANTASSIGNMENT("RedundantAssignment", Implementability.IMPLEMENTABLE, Activation.WARNING),
    REDUNDANTATTRIBUTEPARENTHESES("RedundantAttributeParentheses", Implementability.IMPLEMENTABLE, Activation.HINT),
    REDUNDANTATTRIBUTEUSAGEPROPERTY("RedundantAttributeUsageProperty", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    REDUNDANTBASECONSTRUCTORCALL("RedundantBaseConstructorCall", Implementability.IMPLEMENTABLE, Activation.WARNING),
    REDUNDANTBASEQUALIFIER("RedundantBaseQualifier", Implementability.REJECTED, Activation.WARNING),
    REDUNDANTBLOCK("RedundantBlock", Implementability.IMPLEMENTABLE, Activation.WARNING),
    REDUNDANTBOOLCOMPARE("RedundantBoolCompare", Implementability.IMPLEMENTABLE, Activation.WARNING),
    REDUNDANTCASELABEL("RedundantCaseLabel", Implementability.IMPLEMENTABLE, Activation.WARNING),
    REDUNDANTCAST("RedundantCast", Implementability.IMPLEMENTABLE, Activation.WARNING),
    REDUNDANTCAST_0("RedundantCast.0", Implementability.REJECTED, Activation.WARNING),
    REDUNDANTCATCHCLAUSE("RedundantCatchClause", Implementability.IMPLEMENTABLE, Activation.WARNING),
    REDUNDANTCHECKBEFOREASSIGNMENT("RedundantCheckBeforeAssignment", Implementability.IMPLEMENTABLE, Activation.WARNING),
    REDUNDANTCOLLECTIONINITIALIZERELEMENTBRACES("RedundantCollectionInitializerElementBraces", Implementability.IMPLEMENTABLE, Activation.HINT),
    REDUNDANTCOMMAINATTRIBUTELIST("RedundantCommaInAttributeList", Implementability.IMPLEMENTABLE, Activation.HINT),
    REDUNDANTCOMMAINENUMDECLARATION("RedundantCommaInEnumDeclaration", Implementability.IMPLEMENTABLE, Activation.HINT),
    REDUNDANTCOMMAININITIALIZER("RedundantCommaInInitializer", Implementability.IMPLEMENTABLE, Activation.HINT),
    REDUNDANTCOMPARISONWITHBOOLEAN("RedundantComparisonWithBoolean", Implementability.IMPLEMENTABLE, Activation.WARNING),
    REDUNDANTDECLARATIONSEMICOLON("RedundantDeclarationSemicolon", Implementability.IMPLEMENTABLE, Activation.HINT),
    REDUNDANTDEFAULTMEMBERINITIALIZER("RedundantDefaultMemberInitializer", Implementability.IMPLEMENTABLE, Activation.WARNING),
    REDUNDANTDELEGATECREATION("RedundantDelegateCreation", Implementability.IMPLEMENTABLE, Activation.WARNING),
    REDUNDANTDISABLEWARNINGCOMMENT("RedundantDisableWarningComment", Implementability.IMPLEMENTABLE, Activation.WARNING),
    REDUNDANTELSEBLOCK("RedundantElseBlock", Implementability.IMPLEMENTABLE, Activation.WARNING),
    REDUNDANTEMPTYCONSTRUCTOR("RedundantEmptyConstructor", Implementability.IMPLEMENTABLE, Activation.WARNING),
    REDUNDANTEMPTYDEFAULTSWITCHBRANCH("RedundantEmptyDefaultSwitchBranch", Implementability.IMPLEMENTABLE, Activation.WARNING),
    REDUNDANTEMPTYFINALLYBLOCK("RedundantEmptyFinallyBlock", Implementability.IMPLEMENTABLE, Activation.WARNING),
    REDUNDANTEMPTYOBJECTCREATIONARGUMENTLIST("RedundantEmptyObjectCreationArgumentList", Implementability.IMPLEMENTABLE, Activation.HINT),
    REDUNDANTEMPTYOBJECTORCOLLECTIONINITIALIZER("RedundantEmptyObjectOrCollectionInitializer", Implementability.IMPLEMENTABLE, Activation.WARNING),
    REDUNDANTENUMERABLECASTCALL("RedundantEnumerableCastCall", Implementability.IMPLEMENTABLE, Activation.WARNING),
    REDUNDANTEXPLICITARRAYCREATION("RedundantExplicitArrayCreation", Implementability.IMPLEMENTABLE, Activation.WARNING),
    REDUNDANTEXPLICITARRAYSIZE("RedundantExplicitArraySize", Implementability.IMPLEMENTABLE, Activation.WARNING),
    REDUNDANTEXPLICITNULLABLECREATION("RedundantExplicitNullableCreation", Implementability.IMPLEMENTABLE, Activation.WARNING),
    REDUNDANTEXPLICITPARAMSARRAYCREATION("RedundantExplicitParamsArrayCreation", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    REDUNDANTEXTENDSLISTENTRY("RedundantExtendsListEntry", Implementability.IMPLEMENTABLE, Activation.WARNING),
    REDUNDANTIFELSEBLOCK("RedundantIfElseBlock", Implementability.IMPLEMENTABLE, Activation.HINT),
    REDUNDANTIMMEDIATEDELEGATEINVOCATION("RedundantImmediateDelegateInvocation", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    REDUNDANTINTERMEDIATEVARIABLE("RedundantIntermediateVariable", Implementability.IMPLEMENTABLE, Activation.HINT),
    REDUNDANTJUMPSTATEMENT("RedundantJumpStatement", Implementability.IMPLEMENTABLE, Activation.WARNING),
    REDUNDANTLAMBDAPARAMETERTYPE("RedundantLambdaParameterType", Implementability.IMPLEMENTABLE, Activation.WARNING),
    REDUNDANTLAMBDASIGNATUREPARENTHESES("RedundantLambdaSignatureParentheses", Implementability.REJECTED, Activation.WARNING),
    REDUNDANTLOGICALCONDITIONALEXPRESSIONOPERAND("RedundantLogicalConditionalExpressionOperand", Implementability.IMPLEMENTABLE, Activation.WARNING),
    REDUNDANTNAMEQUALIFIER("RedundantNameQualifier", Implementability.REJECTED, Activation.WARNING),
    REDUNDANTOVERFLOWCHECKINGCONTEXT("RedundantOverflowCheckingContext", Implementability.IMPLEMENTABLE, Activation.WARNING),
    REDUNDANTOVERLOAD_GLOBAL("RedundantOverload.Global", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    REDUNDANTOVERLOAD_LOCAL("RedundantOverload.Local", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    REDUNDANTOVERRIDENMEMBER("RedundantOverridenMember", Implementability.IMPLEMENTABLE, Activation.WARNING),
    REDUNDANTPARAMS("RedundantParams", Implementability.IMPLEMENTABLE, Activation.WARNING),
    REDUNDANTPARENTTYPEDECLARATION("RedundantParentTypeDeclaration", Implementability.IMPLEMENTABLE, Activation.WARNING),
    REDUNDANTPROPERTYPARENTHESES("RedundantPropertyParentheses", Implementability.IMPLEMENTABLE, Activation.HINT),
    REDUNDANTSETTERVALUEPARAMETERDECLARATION("RedundantSetterValueParameterDeclaration", Implementability.IMPLEMENTABLE, Activation.HINT),
    REDUNDANTSTRINGFORMATCALL("RedundantStringFormatCall", Implementability.IMPLEMENTABLE, Activation.WARNING),
    REDUNDANTSTRINGINTERPOLATION("RedundantStringInterpolation", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    REDUNDANTSTRINGTOCHARARRAYCALL("RedundantStringToCharArrayCall", Implementability.IMPLEMENTABLE, Activation.WARNING),
    REDUNDANTTERNARYEXPRESSION("RedundantTernaryExpression", Implementability.IMPLEMENTABLE, Activation.WARNING),
    REDUNDANTTOSTRINGCALL("RedundantToStringCall", Implementability.IMPLEMENTABLE, Activation.WARNING),
    REDUNDANTTOSTRINGCALLFORVALUETYPE("RedundantToStringCallForValueType", Implementability.IMPLEMENTABLE, Activation.HINT),
    REDUNDANTTYPECAST("RedundantTypeCast", Implementability.IMPLEMENTABLE, Activation.WARNING),
    REDUNDANTTYPECASTSTRUCTURAL("RedundantTypeCastStructural", Implementability.IMPLEMENTABLE, Activation.WARNING),
    REDUNDANTUNSAFECONTEXT("RedundantUnsafeContext", Implementability.IMPLEMENTABLE, Activation.WARNING),
    REDUNDANTUSINGDIRECTIVE("RedundantUsingDirective", Implementability.REJECTED, Activation.WARNING),
    REDUNDANTVARIABLETYPESPECIFICATION("RedundantVariableTypeSpecification", Implementability.IMPLEMENTABLE, Activation.HINT),
    REFERENCEEQUALSWITHVALUETYPE("ReferenceEqualsWithValueType", Implementability.IMPLEMENTABLE, Activation.WARNING),
    REGEXPERRORS("RegExpErrors", Implementability.IMPLEMENTABLE, Activation.ERROR),
    REMOVECONSTUCTORINVOCATION("RemoveConstuctorInvocation", Implementability.IMPLEMENTABLE, Activation.DO_NOT_SHOW),
    REMOVEREDUNDANTORSTATEMENT_FALSE("RemoveRedundantOrStatement.False", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    REMOVEREDUNDANTORSTATEMENT_TRUE("RemoveRedundantOrStatement.True", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    REMOVETOLIST_1("RemoveToList.1", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    REMOVETOLIST_2("RemoveToList.2", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    REPLACEINDICINGWITHARRAYDESTRUCTURING("ReplaceIndicingWithArrayDestructuring", Implementability.IMPLEMENTABLE, Activation.HINT),
    REPLACEINDICINGWITHSHORTHANDPROPERTIESAFTERDESTRUCTURING("ReplaceIndicingWithShortHandPropertiesAfterDestructuring", Implementability.IMPLEMENTABLE, Activation.HINT),
    REPLACEUNDEFINEDCHECKINGSERIESWITHOBJECTDESTRUCTURING("ReplaceUndefinedCheckingSeriesWithObjectDestructuring", Implementability.IMPLEMENTABLE, Activation.HINT),
    REPLACEWITHDESTRUCTURINGSWAP("ReplaceWithDestructuringSwap", Implementability.IMPLEMENTABLE, Activation.HINT),
    REPLACEWITHFIRSTORDEFAULT_1("ReplaceWithFirstOrDefault.1", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    REPLACEWITHFIRSTORDEFAULT_2("ReplaceWithFirstOrDefault.2", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    REPLACEWITHFIRSTORDEFAULT_3("ReplaceWithFirstOrDefault.3", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    REPLACEWITHFIRSTORDEFAULT_4("ReplaceWithFirstOrDefault.4", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    REPLACEWITHLASTORDEFAULT_1("ReplaceWithLastOrDefault.1", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    REPLACEWITHLASTORDEFAULT_2("ReplaceWithLastOrDefault.2", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    REPLACEWITHLASTORDEFAULT_3("ReplaceWithLastOrDefault.3", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    REPLACEWITHLASTORDEFAULT_4("ReplaceWithLastOrDefault.4", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    REPLACEWITHOFTYPE_1("ReplaceWithOfType.1", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    REPLACEWITHOFTYPE_2("ReplaceWithOfType.2", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    REPLACEWITHOFTYPE_3("ReplaceWithOfType.3", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    REPLACEWITHOFTYPE_ANY_1("ReplaceWithOfType.Any.1", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    REPLACEWITHOFTYPE_ANY_2("ReplaceWithOfType.Any.2", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    REPLACEWITHOFTYPE_COUNT_1("ReplaceWithOfType.Count.1", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    REPLACEWITHOFTYPE_COUNT_2("ReplaceWithOfType.Count.2", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    REPLACEWITHOFTYPE_FIRST_1("ReplaceWithOfType.First.1", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    REPLACEWITHOFTYPE_FIRST_2("ReplaceWithOfType.First.2", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    REPLACEWITHOFTYPE_FIRSTORDEFAULT_1("ReplaceWithOfType.FirstOrDefault.1", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    REPLACEWITHOFTYPE_FIRSTORDEFAULT_2("ReplaceWithOfType.FirstOrDefault.2", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    REPLACEWITHOFTYPE_LAST_1("ReplaceWithOfType.Last.1", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    REPLACEWITHOFTYPE_LAST_2("ReplaceWithOfType.Last.2", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    REPLACEWITHOFTYPE_LASTORDEFAULT_1("ReplaceWithOfType.LastOrDefault.1", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    REPLACEWITHOFTYPE_LASTORDEFAULT_2("ReplaceWithOfType.LastOrDefault.2", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    REPLACEWITHOFTYPE_LONGCOUNT("ReplaceWithOfType.LongCount", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    REPLACEWITHOFTYPE_SINGLE_1("ReplaceWithOfType.Single.1", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    REPLACEWITHOFTYPE_SINGLE_2("ReplaceWithOfType.Single.2", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    REPLACEWITHOFTYPE_SINGLEORDEFAULT_1("ReplaceWithOfType.SingleOrDefault.1", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    REPLACEWITHOFTYPE_SINGLEORDEFAULT_2("ReplaceWithOfType.SingleOrDefault.2", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    REPLACEWITHOFTYPE_WHERE("ReplaceWithOfType.Where", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    REPLACEWITHSIMPLEASSIGNMENT_FALSE("ReplaceWithSimpleAssignment.False", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    REPLACEWITHSIMPLEASSIGNMENT_TRUE("ReplaceWithSimpleAssignment.True", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    REPLACEWITHSINGLEASSIGNMENT_FALSE("ReplaceWithSingleAssignment.False", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    REPLACEWITHSINGLEASSIGNMENT_TRUE("ReplaceWithSingleAssignment.True", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    REPLACEWITHSINGLECALLTOANY("ReplaceWithSingleCallToAny", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    REPLACEWITHSINGLECALLTOCOUNT("ReplaceWithSingleCallToCount", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    REPLACEWITHSINGLECALLTOFIRST("ReplaceWithSingleCallToFirst", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    REPLACEWITHSINGLECALLTOFIRSTORDEFAULT("ReplaceWithSingleCallToFirstOrDefault", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    REPLACEWITHSINGLECALLTOLAST("ReplaceWithSingleCallToLast", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    REPLACEWITHSINGLECALLTOLASTORDEFAULT("ReplaceWithSingleCallToLastOrDefault", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    REPLACEWITHSINGLECALLTOSINGLE("ReplaceWithSingleCallToSingle", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    REPLACEWITHSINGLECALLTOSINGLEORDEFAULT("ReplaceWithSingleCallToSingleOrDefault", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    REPLACEWITHSINGLEORDEFAULT_1("ReplaceWithSingleOrDefault.1", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    REPLACEWITHSINGLEORDEFAULT_2("ReplaceWithSingleOrDefault.2", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    REPLACEWITHSINGLEORDEFAULT_3("ReplaceWithSingleOrDefault.3", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    REPLACEWITHSINGLEORDEFAULT_4("ReplaceWithSingleOrDefault.4", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    REPLACEWITHSTRINGISNULLOREMPTY("ReplaceWithStringIsNullOrEmpty", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    REQUIREDBASETYPESCONFLICT("RequiredBaseTypesConflict", Implementability.REJECTED, Activation.WARNING),
    REQUIREDBASETYPESDIRECTCONFLICT("RequiredBaseTypesDirectConflict", Implementability.REJECTED, Activation.WARNING),
    REQUIREDBASETYPESISNOTINHERITED("RequiredBaseTypesIsNotInherited", Implementability.REJECTED, Activation.WARNING),
    REQUIRESFALLBACKCOLOR("RequiresFallbackColor", Implementability.IMPLEMENTABLE, Activation.WARNING),
    RESOURCEITEMNOTRESOLVED("ResourceItemNotResolved", Implementability.IMPLEMENTABLE, Activation.ERROR),
    RESOURCENOTRESOLVED("ResourceNotResolved", Implementability.IMPLEMENTABLE, Activation.ERROR),
    RESXNOTRESOLVED("ResxNotResolved", Implementability.REJECTED, Activation.WARNING),
    RETURNTYPECANBEENUMERABLE_GLOBAL("ReturnTypeCanBeEnumerable.Global", Implementability.IMPLEMENTABLE, Activation.HINT),
    RETURNTYPECANBEENUMERABLE_LOCAL("ReturnTypeCanBeEnumerable.Local", Implementability.IMPLEMENTABLE, Activation.HINT),
    RETURNVALUEOFPUREMETHODISNOTUSED("ReturnValueOfPureMethodIsNotUsed", Implementability.IMPLEMENTABLE, Activation.WARNING),
    SAMEIMPORTSWITHDIFFERENTNAME("SameImportsWithDifferentName", Implementability.IMPLEMENTABLE, Activation.WARNING),
    SAMEVARIABLEASSIGNMENT("SameVariableAssignment", Implementability.IMPLEMENTABLE, Activation.WARNING),
    SEALEDMEMBERINSEALEDCLASS("SealedMemberInSealedClass", Implementability.IMPLEMENTABLE, Activation.WARNING),
    SEVICECONTRACTWITHOUTOPERATIONS("SeviceContractWithoutOperations", Implementability.IMPLEMENTABLE, Activation.WARNING),
    SIMILARANONYMOUSTYPENEARBY("SimilarAnonymousTypeNearby", Implementability.IMPLEMENTABLE, Activation.HINT),
    SIMILAREXPRESSIONSCOMPARISON("SimilarExpressionsComparison", Implementability.IMPLEMENTABLE, Activation.WARNING),
    SIMPLIFYCONDITIONALOPERATOR("SimplifyConditionalOperator", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    SIMPLIFYCONDITIONALTERNARYEXPRESSION("SimplifyConditionalTernaryExpression", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    SIMPLIFYLINQEXPRESSION("SimplifyLinqExpression", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    SPECIFYACULTUREINSTRINGCONVERSIONEXPLICITLY("SpecifyACultureInStringConversionExplicitly", Implementability.IMPLEMENTABLE, Activation.WARNING),
    SPECIFYSTRINGCOMPARISON("SpecifyStringComparison", Implementability.IMPLEMENTABLE, Activation.HINT),
    SPECIFYVARIABLETYPEEXPLICITLY("SpecifyVariableTypeExplicitly", Implementability.IMPLEMENTABLE, Activation.HINT),
    STATICMEMBERINGENERICTYPE("StaticMemberInGenericType", Implementability.IMPLEMENTABLE, Activation.WARNING),
    STATICMEMBERINITIALIZERREFERESTOMEMBERBELOW("StaticMemberInitializerReferesToMemberBelow", Implementability.IMPLEMENTABLE, Activation.WARNING),
    STRINGCOMPAREISCULTURESPECIFIC_1("StringCompareIsCultureSpecific.1", Implementability.IMPLEMENTABLE, Activation.WARNING),
    STRINGCOMPAREISCULTURESPECIFIC_2("StringCompareIsCultureSpecific.2", Implementability.IMPLEMENTABLE, Activation.WARNING),
    STRINGCOMPAREISCULTURESPECIFIC_3("StringCompareIsCultureSpecific.3", Implementability.IMPLEMENTABLE, Activation.WARNING),
    STRINGCOMPAREISCULTURESPECIFIC_4("StringCompareIsCultureSpecific.4", Implementability.IMPLEMENTABLE, Activation.WARNING),
    STRINGCOMPAREISCULTURESPECIFIC_5("StringCompareIsCultureSpecific.5", Implementability.IMPLEMENTABLE, Activation.WARNING),
    STRINGCOMPAREISCULTURESPECIFIC_6("StringCompareIsCultureSpecific.6", Implementability.IMPLEMENTABLE, Activation.WARNING),
    STRINGCOMPARETOISCULTURESPECIFIC("StringCompareToIsCultureSpecific", Implementability.IMPLEMENTABLE, Activation.WARNING),
    STRINGCONCATENATIONTOTEMPLATESTRING("StringConcatenationToTemplateString", Implementability.IMPLEMENTABLE, Activation.HINT),
    STRINGENDSWITHISCULTURESPECIFIC("StringEndsWithIsCultureSpecific", Implementability.IMPLEMENTABLE, Activation.DO_NOT_SHOW),
    STRINGINDEXOFISCULTURESPECIFIC_1("StringIndexOfIsCultureSpecific.1", Implementability.IMPLEMENTABLE, Activation.WARNING),
    STRINGINDEXOFISCULTURESPECIFIC_2("StringIndexOfIsCultureSpecific.2", Implementability.IMPLEMENTABLE, Activation.WARNING),
    STRINGINDEXOFISCULTURESPECIFIC_3("StringIndexOfIsCultureSpecific.3", Implementability.IMPLEMENTABLE, Activation.WARNING),
    STRINGLASTINDEXOFISCULTURESPECIFIC_1("StringLastIndexOfIsCultureSpecific.1", Implementability.IMPLEMENTABLE, Activation.WARNING),
    STRINGLASTINDEXOFISCULTURESPECIFIC_2("StringLastIndexOfIsCultureSpecific.2", Implementability.IMPLEMENTABLE, Activation.WARNING),
    STRINGLASTINDEXOFISCULTURESPECIFIC_3("StringLastIndexOfIsCultureSpecific.3", Implementability.IMPLEMENTABLE, Activation.WARNING),
    STRINGLITERALWRONGQUOTES("StringLiteralWrongQuotes", Implementability.IMPLEMENTABLE, Activation.HINT),
    STRINGSTARTSWITHISCULTURESPECIFIC("StringStartsWithIsCultureSpecific", Implementability.IMPLEMENTABLE, Activation.DO_NOT_SHOW),
    STRUCTURALSEARCH("StructuralSearch", Implementability.IMPLEMENTABLE, Activation.UNKNOWN),
    SUGGESTBASETYPEFORPARAMETER("SuggestBaseTypeForParameter", Implementability.REJECTED, Activation.HINT),
    SUGGESTVARORTYPE_BUILTINTYPES("SuggestVarOrType_BuiltInTypes", Implementability.IMPLEMENTABLE, Activation.HINT),
    SUGGESTVARORTYPE_ELSEWHERE("SuggestVarOrType_Elsewhere", Implementability.IMPLEMENTABLE, Activation.HINT),
    SUGGESTVARORTYPE_SIMPLETYPES("SuggestVarOrType_SimpleTypes", Implementability.IMPLEMENTABLE, Activation.HINT),
    SUPERCALL("SuperCall", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    SUSPICIOUSINSTANCEOFCHECK("SuspiciousInstanceofCheck", Implementability.IMPLEMENTABLE, Activation.WARNING),
    SUSPICIOUSLAMBDABLOCK("SuspiciousLambdaBlock", Implementability.IMPLEMENTABLE, Activation.WARNING),
    SUSPICIOUSTHISUSAGE("SuspiciousThisUsage", Implementability.IMPLEMENTABLE, Activation.WARNING),
    SUSPICIOUSTYPECONVERSION_GLOBAL("SuspiciousTypeConversion.Global", Implementability.IMPLEMENTABLE, Activation.WARNING),
    SUSPICIOUSTYPEOFCHECK("SuspiciousTypeofCheck", Implementability.IMPLEMENTABLE, Activation.WARNING),
    SWITCHSTATEMENTMISSINGSOMECASES("SwitchStatementMissingSomeCases", Implementability.IMPLEMENTABLE, Activation.HINT),
    SYNTAXISNOTALLOWED("SyntaxIsNotAllowed", Implementability.IMPLEMENTABLE, Activation.WARNING),
    TAILRECURSIVECALL("TailRecursiveCall", Implementability.IMPLEMENTABLE, Activation.HINT),
    TASKSNOTLOADED("TasksNotLoaded", Implementability.REJECTED, Activation.WARNING),
    TERNARYCANBEREPLACEDBYITSCONDITION("TernaryCanBeReplacedByItsCondition", Implementability.IMPLEMENTABLE, Activation.WARNING),
    THREADSTATICATINSTANCEFIELD("ThreadStaticAtInstanceField", Implementability.IMPLEMENTABLE, Activation.WARNING),
    THREADSTATICFIELDHASINITIALIZER("ThreadStaticFieldHasInitializer", Implementability.IMPLEMENTABLE, Activation.WARNING),
    TOOWIDELOCALVARIABLESCOPE("TooWideLocalVariableScope", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    TRYCASTALWAYSSUCCEEDS("TryCastAlwaysSucceeds", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    TRYCASTANDCHECKFORNULL_0("TryCastAndCheckForNull.0", Implementability.IMPLEMENTABLE, Activation.WARNING),
    TRYCASTANDCHECKFORNULL_1("TryCastAndCheckForNull.1", Implementability.IMPLEMENTABLE, Activation.WARNING),
    TRYSTATEMENTSCANBEMERGED("TryStatementsCanBeMerged", Implementability.IMPLEMENTABLE, Activation.HINT),
    TYPEGUARDDOESNTAFFECTANYTHING("TypeGuardDoesntAffectAnything", Implementability.IMPLEMENTABLE, Activation.WARNING),
    TYPEPARAMETERCANBEVARIANT("TypeParameterCanBeVariant", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    TYPEPARAMETERHIDESTYPEPARAMFROMOUTERSCOPE("TypeParameterHidesTypeParamFromOuterScope", Implementability.IMPLEMENTABLE, Activation.WARNING),
    UKNOWNTASKATTRIBUTE("UknownTaskAttribute", Implementability.REJECTED, Activation.WARNING),
    UNASSIGNEDFIELD_COMPILER("UnassignedField.Compiler", Implementability.REJECTED, Activation.WARNING),
    UNASSIGNEDFIELD_GLOBAL("UnassignedField.Global", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    UNASSIGNEDFIELD_LOCAL("UnassignedField.Local", Implementability.IMPLEMENTABLE, Activation.WARNING),
    UNASSIGNEDGETONLYAUTOPROPERTY("UnassignedGetOnlyAutoProperty", Implementability.IMPLEMENTABLE, Activation.WARNING),
    UNASSIGNEDREADONLYFIELD("UnassignedReadonlyField", Implementability.IMPLEMENTABLE, Activation.WARNING),
    UNASSIGNEDREADONLYFIELD_COMPILER("UnassignedReadonlyField.Compiler", Implementability.REJECTED, Activation.WARNING),
    UNDECLAREDGLOBALVARIABLEUSING("UndeclaredGlobalVariableUsing", Implementability.IMPLEMENTABLE, Activation.WARNING),
    UNKNOWNCSSCLASS("UnknownCssClass", Implementability.IMPLEMENTABLE, Activation.WARNING),
    UNKNOWNCSSVENDOREXTENSION("UnknownCssVendorExtension", Implementability.IMPLEMENTABLE, Activation.HINT),
    UNKNOWNITEMGROUP("UnknownItemGroup", Implementability.REJECTED, Activation.WARNING),
    UNKNOWNMETADATA("UnknownMetadata", Implementability.REJECTED, Activation.WARNING),
    UNKNOWNOUTPUTPARAMETER("UnknownOutputParameter", Implementability.REJECTED, Activation.WARNING),
    UNKNOWNPROPERTY("UnknownProperty", Implementability.REJECTED, Activation.WARNING),
    UNKNOWNTARGET("UnknownTarget", Implementability.REJECTED, Activation.WARNING),
    UNKNOWNTASK("UnknownTask", Implementability.REJECTED, Activation.WARNING),
    UNNECESSARYWHITESPACE("UnnecessaryWhitespace", Implementability.IMPLEMENTABLE, Activation.DO_NOT_SHOW),
    UNREACHABLECODE("UnreachableCode", Implementability.REJECTED, Activation.WARNING),
    UNRESOLVEDSYMBOLINSTRINGLITERAL("UnresolvedSymbolInStringLiteral", Implementability.IMPLEMENTABLE, Activation.ERROR),
    UNSAFECOMMAINOBJECTPROPERTIESLIST("UnsafeCommaInObjectPropertiesList", Implementability.IMPLEMENTABLE, Activation.WARNING),
    UNSUPPORTEDREQUIREDBASETYPE("UnsupportedRequiredBaseType", Implementability.REJECTED, Activation.WARNING),
    UNUSEDANONYMOUSMETHODSIGNATURE("UnusedAnonymousMethodSignature", Implementability.IMPLEMENTABLE, Activation.WARNING),
    UNUSEDAUTOPROPERTYACCESSOR_GLOBAL("UnusedAutoPropertyAccessor.Global", Implementability.IMPLEMENTABLE, Activation.WARNING),
    UNUSEDAUTOPROPERTYACCESSOR_LOCAL("UnusedAutoPropertyAccessor.Local", Implementability.IMPLEMENTABLE, Activation.WARNING),
    UNUSEDFIELD_COMPILER("UnusedField.Compiler", Implementability.REJECTED, Activation.WARNING),
    UNUSEDIMPORTCLAUSE("UnusedImportClause", Implementability.REJECTED, Activation.WARNING),
    UNUSEDINHERITEDPARAMETER("UnusedInheritedParameter", Implementability.IMPLEMENTABLE, Activation.HINT),
    UNUSEDLABEL("UnusedLabel", Implementability.REJECTED, Activation.WARNING),
    UNUSEDLOCALIMPORT("UnusedLocalImport", Implementability.IMPLEMENTABLE, Activation.WARNING),
    UNUSEDMEMBER_GLOBAL("UnusedMember.Global", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    UNUSEDMEMBER_LOCAL("UnusedMember.Local", Implementability.IMPLEMENTABLE, Activation.WARNING),
    UNUSEDMEMBERHIEARCHY_GLOBAL("UnusedMemberHiearchy.Global", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    UNUSEDMEMBERHIEARCHY_LOCAL("UnusedMemberHiearchy.Local", Implementability.IMPLEMENTABLE, Activation.WARNING),
    UNUSEDMEMBERINSUPER_GLOBAL("UnusedMemberInSuper.Global", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    UNUSEDMEMBERINSUPER_LOCAL("UnusedMemberInSuper.Local", Implementability.IMPLEMENTABLE, Activation.WARNING),
    UNUSEDMETHODRETURNVALUE_GLOBAL("UnusedMethodReturnValue.Global", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    UNUSEDMETHODRETURNVALUE_LOCAL("UnusedMethodReturnValue.Local", Implementability.IMPLEMENTABLE, Activation.WARNING),
    UNUSEDPARAMETER("UnusedParameter", Implementability.IMPLEMENTABLE, Activation.WARNING),
    UNUSEDPARAMETER_GLOBAL("UnusedParameter.Global", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    UNUSEDPARAMETER_LOCAL("UnusedParameter.Local", Implementability.IMPLEMENTABLE, Activation.WARNING),
    UNUSEDPROPERTY("UnusedProperty", Implementability.IMPLEMENTABLE, Activation.WARNING),
    UNUSEDTYPEPARAMETER("UnusedTypeParameter", Implementability.IMPLEMENTABLE, Activation.WARNING),
    UNUSEDVARIABLE("UnusedVariable", Implementability.IMPLEMENTABLE, Activation.WARNING),
    UNUSEDVARIABLE_COMPILER("UnusedVariable.Compiler", Implementability.REJECTED, Activation.WARNING),
    USAGEOFDEFINITELYUNASSIGNEDVALUE("UsageOfDefinitelyUnassignedValue", Implementability.IMPLEMENTABLE, Activation.WARNING),
    USAGEOFPOSSIBLYUNASSIGNEDVALUE("UsageOfPossiblyUnassignedValue", Implementability.IMPLEMENTABLE, Activation.WARNING),
    USEARRAYCREATIONEXPRESSION_1("UseArrayCreationExpression.1", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    USEARRAYCREATIONEXPRESSION_2("UseArrayCreationExpression.2", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    USEASINSTEADOFTYPECAST("UseAsInsteadOfTypeCast", Implementability.IMPLEMENTABLE, Activation.HINT),
    USECOLLECTIONCOUNTPROPERTY("UseCollectionCountProperty", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    USEIMPLICITBYVALMODIFIER("UseImplicitByValModifier", Implementability.IMPLEMENTABLE, Activation.HINT),
    USEIMPLICITLYTYPEDVARIABLE("UseImplicitlyTypedVariable", Implementability.IMPLEMENTABLE, Activation.DO_NOT_SHOW),
    USEIMPLICITLYTYPEDVARIABLEEVIDENT("UseImplicitlyTypedVariableEvident", Implementability.IMPLEMENTABLE, Activation.HINT),
    USEINDEXEDPROPERTY("UseIndexedProperty", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    USEISOPERATOR_1("UseIsOperator.1", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    USEISOPERATOR_2("UseIsOperator.2", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    USEMETHODANY_0("UseMethodAny.0", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    USEMETHODANY_1("UseMethodAny.1", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    USEMETHODANY_2("UseMethodAny.2", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    USEMETHODANY_3("UseMethodAny.3", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    USEMETHODANY_4("UseMethodAny.4", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    USEMETHODISINSTANCEOFTYPE("UseMethodIsInstanceOfType", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    USENAMEOFEXPRESSION("UseNameofExpression", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    USENULLPROPAGATION("UseNullPropagation", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    USENULLPROPAGATIONWHENPOSSIBLE("UseNullPropagationWhenPossible", Implementability.IMPLEMENTABLE, Activation.DO_NOT_SHOW),
    USEOBJECTORCOLLECTIONINITIALIZER("UseObjectOrCollectionInitializer", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    USEOFPOSSIBLYUNASSIGNEDPROPERTY("UseOfPossiblyUnassignedProperty", Implementability.IMPLEMENTABLE, Activation.WARNING),
    USESTRINGINTERPOLATION("UseStringInterpolation", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    USINGOFRESERVEDWORDERROR("UsingOfReservedWordError", Implementability.IMPLEMENTABLE, Activation.ERROR),
    VALUEPARAMETERNOTUSED("ValueParameterNotUsed", Implementability.IMPLEMENTABLE, Activation.WARNING),
    VARIABLECANBEMADECONST("VariableCanBeMadeConst", Implementability.IMPLEMENTABLE, Activation.HINT),
    VARIABLECANBEMADELET("VariableCanBeMadeLet", Implementability.IMPLEMENTABLE, Activation.HINT),
    VARIABLECANBEMOVEDTOINNERBLOCK("VariableCanBeMovedToInnerBlock", Implementability.IMPLEMENTABLE, Activation.HINT),
    VARIABLEUSEDBEFOREDECLARED("VariableUsedBeforeDeclared", Implementability.IMPLEMENTABLE, Activation.WARNING),
    VARIABLEUSEDININNERSCOPEBEFOREDECLARED("VariableUsedInInnerScopeBeforeDeclared", Implementability.IMPLEMENTABLE, Activation.WARNING),
    VARIABLEUSEDOUTOFSCOPE("VariableUsedOutOfScope", Implementability.IMPLEMENTABLE, Activation.WARNING),
    VBUNREACHABLECODE("VbUnreachableCode", Implementability.IMPLEMENTABLE, Activation.WARNING),
    VIRTUALMEMBERCALLINCONTRUCTOR("VirtualMemberCallInContructor", Implementability.IMPLEMENTABLE, Activation.WARNING),
    VIRTUALMEMBERNEVEROVERRIDEN_GLOBAL("VirtualMemberNeverOverriden.Global", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    VIRTUALMEMBERNEVEROVERRIDEN_LOCAL("VirtualMemberNeverOverriden.Local", Implementability.IMPLEMENTABLE, Activation.SUGGESTION),
    VOIDMETHODWITHMUSTUSERETURNVALUEATTRIBUTE("VoidMethodWithMustUseReturnValueAttribute", Implementability.IMPLEMENTABLE, Activation.WARNING),
    WITHSTATEMENTUSINGERROR("WithStatementUsingError", Implementability.IMPLEMENTABLE, Activation.ERROR),
    WRONGMETADATAUSE("WrongMetadataUse", Implementability.REJECTED, Activation.DO_NOT_SHOW),
    WRONGPUBLICMODIFIERSPECIFICATION("WrongPublicModifierSpecification", Implementability.IMPLEMENTABLE, Activation.HINT),
    WRONGREQUIRERELATIVEPATH("WrongRequireRelativePath", Implementability.IMPLEMENTABLE, Activation.HINT);


    private Implementability implementability;
    private Activation activation;
    private String title;

    ReSharperRule(String title, Implementability implementability, Activation activation) {
      this.activation = activation;
      this.implementability = implementability;
      this.title = title;
    }

    @Override
    public Implementability getImplementability() {
      return this.implementability;
    }
    @Override
    public String getCodingStandardRuleId() {
      return this.title;
    }
    @Override
    public String getLevel() {
      return this.activation.name().toLowerCase();
    }

  }

}
