language: java
sudo: false

jdk:
  - oraclejdk8

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

install: true
script: ./travis.sh

matrix:
  fast_finish: true

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: false
  webhooks:
    - secure: "Cvc3l6tKXao9somUHuxbhl9u/QDSPzqUs6aI98yaOB/l27768vTRC4hD68MduYe77PGvZ1cEV2a4z6Z8YSj9kY9ky9PNi89oOM2HvnRxp+fECMG4ukB1NTJQpPXMPN+mcmV3gHzeUeYmpPQkV3DwWt2lo2SFKuoTZOTM85qJ1ec="
